name: Deploy using Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Check if the build folder exists
    - name: Check if build folder exists
      run: |
        if [ ! -d "build" ]; then
          echo "Error: Build folder does not exist. Make sure the build step runs successfully."
          exit 1
        fi

    # Set Git user identity
    - name: Set Git user identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Clean gh-pages branch: Check if files exist before attempting to remove them
    - name: Clean gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        
        # Pull remote changes before cleaning
        git pull origin gh-pages --rebase

        # Clean the branch (remove files if necessary)
        git rm -rf .
        git commit --allow-empty -m "Clean branch"
        
        # Push the changes
        git push origin gh-pages

    # Deploy to GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        clean: true
