name: Deploy using Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --passWithNoTests
    - name: Clean gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        git clean -fdx
        git commit --allow-empty -m "Clean branch"
        git push origin gh-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build 
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        clean: true