name: Deploy using Github Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build --if-present

    - name: List files after build
      run: |
        echo "Listing files in the root directory:"
        ls -la
        echo "Listing files in the build directory:"
        ls -la build || echo "No build directory found"

    - name: Check build folder existence
      run: |
        if [ -d "build" ]; then
          echo "Build folder exists"
        else
          echo "Build folder does not exist"
          exit 1
        fi

    - name: Install gh-pages
      run: npm install gh-pages@6.2.0

    - name: Clean old build (if necessary)
      run: git clean -fdx

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" --silent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
