  name: Deploy using Github Actions

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

  jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]

      steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run predeploy
      - run: npm test -- --passWithNoTests

      - name: Check for build changes
        run: |
          diff --exit-code build || echo "Build has changed"


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          clean: true
          single-commit: true

