name: Deploy using Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run predeploy script
      run: npm run predeploy

    - name: Run tests (if applicable)
      run: npm test -- --passWithNoTests

    - name: Check for build changes
      run: |
        diff --exit-code build || echo "Build has changed"

    - name: List build directory
      run: ls -al build

    - name: Check status of gh-pages branch
      run: |
        git fetch origin gh-pages
        git diff --stat origin/gh-pages..HEAD

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        clean: true
        single-commit: true
        branch: gh-pages
        git-config-name: 'github-actions[bot]'
        git-config-email: 'github-actions[bot]@users.noreply.github.com'
